# Customise this file, documentation can be found here:
fastlane_version "1.106.2"

default_platform :ios

WORKSPACE                = "passwordd.xcworkspace"
SCHEME                   = "passwordd"

platform :ios do
  desc "Deliver debug app to emails: or groups:"
  lane :deliver_debug do |options|
    setup
    build(configuration: "Debug")
    deliver_by_crashlytics(emails: options[:emails], groups: options[:groups])
  end

  private_lane :setup do
    cocoapods
  end

  private_lane :build do |options|
    configuration = options[:configuration] || abort("configuration: option is required.")

    gym(
      workspace:            WORKSPACE,
      scheme:               SCHEME,
      clean:                true,
      use_legacy_build_api: true,
      configuration:        configuration
    )
  end

  private_lane :deliver_by_crashlytics do |options|
    emails = options[:emails]
    groups = options[:groups]

    targets = if emails
      { emails: emails }
    elsif groups
      { groups: groups }
    else
      abort("emails: or groups: option is required")
    end

    crashlytics(
      {
        api_token:     ENV["CRASHLYTICS_API_KEY"],
        build_secret:  ENV["CRASHLYTICS_BUILD_SECRET"],
        notifications: true
      }.merge(targets)
    )
  end
end
